// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingFlow.Data.Context;

#nullable disable

namespace TradingFlow.Data.Context.Migrations
{
    [DbContext(typeof(TradingFlowDbContext))]
    [Migration("20260827200638_AddDurableDiscovery")]
    partial class AddDurableDiscovery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Data.Identity.TradingFlowUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Audit.DecisionAuditRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunName");

                    b.HasIndex("Ticker");

                    b.ToTable("DecisionAudits");
                });

            modelBuilder.Entity("TradingFlow.Domain.Discovery.DiscoveryAggregateRecord", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstDiscoveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("AggregateId");

                    b.HasIndex("ScopeId", "Symbol")
                        .IsUnique();

                    b.HasIndex("ScopeId", "IsActive", "ExpiresAtUtc");

                    b.ToTable("discovery_aggregates", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Discovery.DiscoverySnapshotRecord", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDiagnostic")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProviderTimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawReference")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymbolsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SnapshotId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("ScopeId", "SourceKind", "SourceKey", "ObservationId")
                        .IsUnique();

                    b.HasIndex("ScopeId", "SourceKind", "SourceKey", "SourceVersion")
                        .IsUnique();

                    b.ToTable("discovery_snapshots", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Discovery.DiscoverySourceMembershipRecord", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LatestSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("MembershipId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("AggregateId", "SourceKind", "SourceKey")
                        .IsUnique();

                    b.ToTable("discovery_source_memberships", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Earnings.EarningsAnalysisSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AnalyzedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("BreakoutAssessment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("EarningsEventId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EffectiveEpsActual")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EffectiveEpsEstimate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EffectiveEpsSurprisePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EffectiveRevenueActualMillions")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EffectiveRevenueEstimateMillions")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EffectiveRevenueSurprisePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Ema10")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Ema20")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EventReturnPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LatestClose")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LatestCompletedBarAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MacdHistogram")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsHeadline")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsProvider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NewsSentiment")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreReleaseReferenceClose")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreReleaseReferenceHigh")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultAssessment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultDataSource")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResultNewsPublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SlotRelativeVolume")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EarningsEventId", "AnalyzedAtUtc");

                    b.HasIndex("Ticker", "AnalyzedAtUtc");

                    b.ToTable("EarningsAnalysisSnapshots");
                });

            modelBuilder.Entity("TradingFlow.Domain.Earnings.EarningsCalendarEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EpsActual")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EpsEstimate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EpsSurprisePercent")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsScheduleEstimate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MarketCapMillions")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OneDayPriceReactionPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ProviderReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseWindow")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReportDateExchange")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReportedEpsActual")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReportedEpsEstimate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReportedEpsSurprisePercent")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResultFirstSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RevenueActualMillions")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RevenueEstimateMillions")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RevenueSurprisePercent")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ScheduledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceArtifactSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider");

                    b.HasIndex("Ticker");

                    b.HasIndex("ReportDateExchange", "ScheduledAtUtc");

                    b.ToTable("EarningsCalendarEvents");
                });

            modelBuilder.Entity("TradingFlow.Domain.Jobs.PersistedJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunName")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("TradingFlow.Domain.Locking.TickerLockEntity", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PodId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Ticker");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("TickerLocks");
                });

            modelBuilder.Entity("TradingFlow.Domain.News.PersistedNewsItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SentimentScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider");

                    b.HasIndex("Ticker");

                    b.HasIndex("Timestamp");

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("TradingFlow.Domain.Orders.PersistedOrder", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShareQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLossPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TakeProfitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientOrderId");

                    b.HasIndex("RunName");

                    b.HasIndex("Status");

                    b.HasIndex("Ticker");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.CandidateRecord", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("candidate_id");

                    b.Property<decimal?>("BenchmarkReturn")
                        .HasColumnType("TEXT")
                        .HasColumnName("benchmark_return");

                    b.Property<Guid?>("CatalystResultId")
                        .HasColumnType("TEXT")
                        .HasColumnName("catalyst_result_id");

                    b.Property<string>("CodeVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code_version");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("config_hash");

                    b.Property<DateTimeOffset>("DiscoveredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("discovered_at_utc");

                    b.Property<string>("DiscoverySource")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("discovery_source");

                    b.Property<string>("FinvizPreset")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("finviz_preset");

                    b.Property<decimal?>("GapAtr")
                        .HasColumnType("TEXT")
                        .HasColumnName("gap_atr");

                    b.Property<decimal?>("GapPct")
                        .HasColumnType("TEXT")
                        .HasColumnName("gap_pct");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("horizon");

                    b.Property<decimal?>("LastPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_price");

                    b.Property<decimal?>("MarketConfirmationScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("market_confirmation_score");

                    b.Property<decimal?>("MarketExcessReturn")
                        .HasColumnType("TEXT")
                        .HasColumnName("market_excess_return");

                    b.Property<decimal?>("PremarketDollarVolume")
                        .HasColumnType("TEXT")
                        .HasColumnName("premarket_dollar_volume");

                    b.Property<long?>("PremarketVolume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("premarket_volume");

                    b.Property<decimal?>("PreviousClose")
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_close");

                    b.Property<int?>("QuoteAgeMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quote_age_ms");

                    b.Property<string>("RejectReasonsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reject_reasons_json");

                    b.Property<DateTimeOffset>("RevalidatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("revalidated_at_utc");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<decimal?>("SameTimeRvol")
                        .HasColumnType("TEXT")
                        .HasColumnName("same_time_rvol");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.Property<decimal?>("SectorExcessReturn")
                        .HasColumnType("TEXT")
                        .HasColumnName("sector_excess_return");

                    b.Property<decimal?>("SectorReturn")
                        .HasColumnType("TEXT")
                        .HasColumnName("sector_return");

                    b.Property<string>("SelectedStrategy")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_strategy");

                    b.Property<string>("SetupScoresJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("setup_scores_json");

                    b.Property<decimal?>("SpreadBps")
                        .HasColumnType("TEXT")
                        .HasColumnName("spread_bps");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.HasKey("CandidateId");

                    b.HasIndex("CatalystResultId");

                    b.HasIndex("RunId");

                    b.HasIndex("Horizon", "State");

                    b.HasIndex("Symbol", "DiscoveredAtUtc");

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.CatalystResultRecord", b =>
                {
                    b.Property<Guid>("CatalystResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("catalyst_result_id");

                    b.Property<Guid?>("CandidateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("candidate_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("CodeVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code_version");

                    b.Property<decimal>("CompositeScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("composite_score");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("config_hash");

                    b.Property<string>("DedupEvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dedup_evidence_json");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset>("EvaluatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluated_at_utc");

                    b.Property<string>("ModelId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_id");

                    b.Property<string>("PenaltiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("penalties_json");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ProviderArticleId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_article_id");

                    b.Property<string>("RawComponentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_components_json");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.Property<string>("Stage1ProvenanceJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stage1_provenance_json");

                    b.Property<string>("Stage2ProvenanceJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("stage2_provenance_json");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.HasKey("CatalystResultId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("EvaluatedAtUtc");

                    b.HasIndex("RunId");

                    b.HasIndex("ProviderArticleId", "Symbol");

                    b.ToTable("catalyst_results", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.GateEvaluationRecord", b =>
                {
                    b.Property<long>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("evaluation_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("candidate_id");

                    b.Property<string>("ClientOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_order_id");

                    b.Property<string>("CodeVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code_version");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("config_hash");

                    b.Property<DateTimeOffset>("EvaluatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluated_at_utc");

                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("gate_name");

                    b.Property<int>("GateOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gate_order");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("inputs_json");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("passed");

                    b.Property<string>("RejectCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("reject_code");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.HasKey("EvaluationId");

                    b.HasIndex("RejectCode");

                    b.HasIndex("RunId");

                    b.HasIndex("CandidateId", "GateOrder");

                    b.ToTable("gate_evaluations", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.KillSwitchEventRecord", b =>
                {
                    b.Property<long>("KillSwitchEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("kill_switch_event_id");

                    b.Property<string>("Actor")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<string>("CodeVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code_version");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("config_hash");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("details_json");

                    b.Property<bool>("FlattenRequested")
                        .HasColumnType("INTEGER")
                        .HasColumnName("flatten_requested");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.Property<string>("SwitchType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("switch_type");

                    b.Property<string>("Transition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("transition");

                    b.HasKey("KillSwitchEventId");

                    b.HasIndex("RunId");

                    b.HasIndex("SwitchType", "OccurredAtUtc");

                    b.ToTable("kill_switch_events", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.OrderEventRecord", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_id");

                    b.Property<string>("BrokerOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_order_id");

                    b.Property<DateTimeOffset?>("BrokerTimestampUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_timestamp_utc");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_order_id");

                    b.Property<string>("CodeVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code_version");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("config_hash");

                    b.Property<decimal?>("FillPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("fill_price");

                    b.Property<decimal?>("FilledQuantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("filled_quantity");

                    b.Property<DateTimeOffset>("LocalTimestampUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("local_timestamp_utc");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("new_state");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<string>("PreviousState")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_state");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("EventId");

                    b.HasIndex("BrokerOrderId");

                    b.HasIndex("RunId");

                    b.HasIndex("ClientOrderId", "LocalTimestampUtc");

                    b.ToTable("order_events", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.OrderIntentRecord", b =>
                {
                    b.Property<Guid>("IntentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("intent_id");

                    b.Property<Guid?>("CandidateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("candidate_id");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_order_id");

                    b.Property<string>("CodeVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code_version");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("config_hash");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal?>("LimitPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("limit_price");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_type");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("request_json");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_quantity");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence_number");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_date");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("side");

                    b.Property<decimal?>("StopPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_price");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<string>("TimeInForce")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("time_in_force");

                    b.HasKey("IntentId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("RunId");

                    b.HasIndex("Symbol", "CreatedAtUtc");

                    b.HasIndex("StrategyId", "Side", "Symbol", "SessionDate", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("order_intents", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.PositionEventRecord", b =>
                {
                    b.Property<long>("PositionEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_event_id");

                    b.Property<string>("BrokerOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_order_id");

                    b.Property<DateTimeOffset>("BrokerTimestampUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_timestamp_utc");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_order_id");

                    b.Property<string>("CodeVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code_version");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("config_hash");

                    b.Property<string>("ExecutionId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_id");

                    b.Property<string>("ExecutionStrategyId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_strategy_id");

                    b.Property<decimal>("FillPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("fill_price");

                    b.Property<decimal>("FillQuantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("fill_quantity");

                    b.Property<DateTimeOffset>("LocalTimestampUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("local_timestamp_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<decimal>("QuantityAfter")
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity_after");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("side");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.HasKey("PositionEventId");

                    b.HasIndex("BrokerOrderId");

                    b.HasIndex("ExecutionId")
                        .IsUnique();

                    b.HasIndex("RunId");

                    b.HasIndex("Symbol", "PositionEventId");

                    b.ToTable("position_events", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.ProductionRun", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<string>("CodeVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code_version");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("config_hash");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at_utc");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("profile");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("RunId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.ReconciliationRecord", b =>
                {
                    b.Property<Guid>("ReconciliationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("reconciliation_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("acknowledged_by");

                    b.Property<string>("AcknowledgementReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("acknowledgement_reason");

                    b.Property<string>("BrokerSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_snapshot_json");

                    b.Property<string>("CodeVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code_version");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("config_hash");

                    b.Property<string>("DiffHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("diff_hash");

                    b.Property<string>("DiffJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("diff_json");

                    b.Property<string>("LocalSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("local_snapshot_json");

                    b.Property<bool>("RequiresAcknowledgement")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requires_acknowledgement");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("ReconciliationId");

                    b.HasIndex("RequiresAcknowledgement")
                        .IsUnique()
                        .HasFilter("requires_acknowledgement = 1");

                    b.HasIndex("RunId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("reconciliations", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.RiskEventRecord", b =>
                {
                    b.Property<long>("RiskEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("risk_event_id");

                    b.Property<string>("CodeVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code_version");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("config_hash");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("details_json");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<decimal?>("LimitValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("limit_value");

                    b.Property<decimal?>("ObservedValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("observed_value");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.HasKey("RiskEventId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("RunId");

                    b.HasIndex("EventType", "Severity");

                    b.ToTable("risk_events", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Portfolio.AdvisoryPortfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdvisoryPortfolios", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Portfolio.AdvisoryPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LastMlScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRecommendation")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastScoredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shares")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("Ticker");

                    b.ToTable("AdvisoryPositions", (string)null);
                });

            modelBuilder.Entity("TradingFlow.Domain.Wishlists.ScreenerPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AverageMlScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ScreenerPresets");
                });

            modelBuilder.Entity("TradingFlow.Domain.Wishlists.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeExtendedHours")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsObserved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("IsObserved");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("TradingFlow.Domain.Wishlists.WishlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ticker");

                    b.HasIndex("WishlistId", "Ticker")
                        .IsUnique();

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("TradingFlow.Domain.Wishlists.WishlistSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsHeadline")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsProvider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("Ticker");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistSignals");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TradingFlow.Data.Identity.TradingFlowUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TradingFlow.Data.Identity.TradingFlowUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingFlow.Data.Identity.TradingFlowUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TradingFlow.Data.Identity.TradingFlowUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingFlow.Domain.Discovery.DiscoverySourceMembershipRecord", b =>
                {
                    b.HasOne("TradingFlow.Domain.Discovery.DiscoveryAggregateRecord", "Aggregate")
                        .WithMany("Sources")
                        .HasForeignKey("AggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aggregate");
                });

            modelBuilder.Entity("TradingFlow.Domain.Earnings.EarningsAnalysisSnapshot", b =>
                {
                    b.HasOne("TradingFlow.Domain.Earnings.EarningsCalendarEvent", null)
                        .WithMany()
                        .HasForeignKey("EarningsEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.CandidateRecord", b =>
                {
                    b.HasOne("TradingFlow.Domain.Persistence.ProductionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.CatalystResultRecord", b =>
                {
                    b.HasOne("TradingFlow.Domain.Persistence.ProductionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.GateEvaluationRecord", b =>
                {
                    b.HasOne("TradingFlow.Domain.Persistence.ProductionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.KillSwitchEventRecord", b =>
                {
                    b.HasOne("TradingFlow.Domain.Persistence.ProductionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.OrderEventRecord", b =>
                {
                    b.HasOne("TradingFlow.Domain.Persistence.ProductionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.OrderIntentRecord", b =>
                {
                    b.HasOne("TradingFlow.Domain.Persistence.ProductionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.PositionEventRecord", b =>
                {
                    b.HasOne("TradingFlow.Domain.Persistence.ProductionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.ReconciliationRecord", b =>
                {
                    b.HasOne("TradingFlow.Domain.Persistence.ProductionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingFlow.Domain.Persistence.RiskEventRecord", b =>
                {
                    b.HasOne("TradingFlow.Domain.Persistence.ProductionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingFlow.Domain.Portfolio.AdvisoryPosition", b =>
                {
                    b.HasOne("TradingFlow.Domain.Portfolio.AdvisoryPortfolio", "Portfolio")
                        .WithMany("Positions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("TradingFlow.Domain.Wishlists.WishlistItem", b =>
                {
                    b.HasOne("TradingFlow.Domain.Wishlists.Wishlist", "Wishlist")
                        .WithMany("Items")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("TradingFlow.Domain.Wishlists.WishlistSignal", b =>
                {
                    b.HasOne("TradingFlow.Domain.Wishlists.Wishlist", "Wishlist")
                        .WithMany()
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("TradingFlow.Domain.Discovery.DiscoveryAggregateRecord", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("TradingFlow.Domain.Portfolio.AdvisoryPortfolio", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("TradingFlow.Domain.Wishlists.Wishlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
