namespace TradingFlow.Web.Models;

public sealed record EarningsCalendarResponse(
    DateTimeOffset GeneratedAtUtc,
    string OperatorTimeZone,
    string ExchangeTimeZone,
    DateOnly NextBusinessDate,
    string NextBusinessDateLabel,
    bool MonitoringActive,
    int MonitoringIntervalSeconds,
    DateTimeOffset? LastAnalysisUtc,
    DateTimeOffset NewsWindowStartUtc,
    DateTimeOffset NewsWindowEndUtc,
    string NewsWindowLabel,
    EarningsFilterStateResponse Filters,
    IReadOnlyList<EarningsNewsEvidenceResponse> News,
    IReadOnlyList<EarningsCalendarItemResponse> Items);

public sealed record EarningsFilterStateResponse(
    string Session,
    string MarketCap,
    IReadOnlyList<EarningsFilterOptionResponse> Sessions,
    IReadOnlyList<EarningsFilterOptionResponse> MarketCaps);

public sealed record EarningsFilterOptionResponse(
    string Value,
    string Label,
    int Count);

public sealed record EarningsNewsEvidenceResponse(
    DateTimeOffset PublishedAtUtc,
    string Tickers,
    string Category,
    decimal SentimentScore,
    string SentimentLabel,
    string Headline,
    string? Summary,
    string Provider,
    string? Source,
    string? Url,
    string WhyItMatters);

public sealed record EarningsCalendarItemResponse(
    string Id,
    string Ticker,
    string CompanyName,
    string DayGroup,
    DateTimeOffset ScheduledAtUtc,
    string ScheduledUtcText,
    string ScheduledNewYorkText,
    string ReleaseWindow,
    string ReleaseWindowLabel,
    bool IsScheduleEstimate,
    decimal? MarketCapMillions,
    string MarketCapBand,
    decimal? EpsEstimate,
    decimal? EpsActual,
    decimal? EpsSurprisePercent,
    string EpsOutcome,
    string EpsOutcomeLabel,
    decimal? RevenueEstimateMillions,
    decimal? RevenueActualMillions,
    decimal? RevenueSurprisePercent,
    string Provider,
    string SourceUrl,
    DateTimeOffset ProviderReceivedAtUtc,
    DateTimeOffset? ResultFirstSeenAtUtc,
    string ResultAssessment,
    string BreakoutAssessment,
    string AssessmentLabel,
    string AnalysisReason,
    DateTimeOffset? ResultNewsPublishedAtUtc,
    string? NewsHeadline,
    string? NewsUrl,
    string? NewsProvider,
    decimal? NewsSentiment,
    DateTimeOffset? LatestCompletedBarAtUtc,
    string? LatestMarketSession,
    decimal? PreReleaseReferenceHigh,
    decimal? PreReleaseReferenceClose,
    decimal? LatestClose,
    decimal? EventReturnPercent,
    decimal? Ema10,
    decimal? Ema20,
    decimal? MacdHistogram,
    decimal? SlotRelativeVolume,
    PreviousEarningsResultResponse? PreviousEarnings);

public sealed record PreviousEarningsResultResponse(
    DateOnly ReportDateExchange,
    DateTimeOffset ScheduledAtUtc,
    string ReleaseWindowLabel,
    decimal? EpsEstimate,
    decimal? EpsActual,
    decimal? EpsSurprisePercent,
    string EpsOutcome,
    string EpsOutcomeLabel,
    decimal? RevenueEstimateMillions,
    decimal? RevenueActualMillions,
    decimal? RevenueSurprisePercent,
    decimal? OneDayPriceReactionPercent,
    string Provider,
    string SourceUrl,
    DateTimeOffset ProviderReceivedAtUtc);
