apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: trading-flow-paper-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "00000000-0000-0000-0000-000000000002"
    keyvaultName: "kv-tradingflow-paper"
    tenantId: "00000000-0000-0000-0000-000000000000"
    objects: |
      array:
        - |
          objectName: alpaca-paper-key-id
          objectType: secret
        - |
          objectName: alpaca-paper-secret-key
          objectType: secret
        - |
          objectName: finviz-api-key
          objectType: secret
        - |
          objectName: tradingflow-warmup-container-sas-url
          objectType: secret
  secretObjects:
    - secretName: trading-flow-paper-secrets
      type: Opaque
      data:
        - objectName: alpaca-paper-key-id
          key: ALPACA_KEY_ID
        - objectName: alpaca-paper-secret-key
          key: ALPACA_SECRET_KEY
        - objectName: finviz-api-key
          key: FINVIZ_API_KEY
        - objectName: tradingflow-warmup-container-sas-url
          key: Warmup__BlobContainerSasUrl
