apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trading-flow-data
  namespace: trading-flow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trading-flow-ui-runs
  namespace: trading-flow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 10Gi
