<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TradingFlow.Domain\TradingFlow.Domain.csproj" />
    <ProjectReference Include="..\TradingFlow.Engine\TradingFlow.Engine.csproj" />
    <ProjectReference Include="..\TradingFlow.Data\TradingFlow.Data.csproj" />
    <ProjectReference Include="..\TradingFlow.Alpaca\TradingFlow.Alpaca.csproj" />
    <ProjectReference Include="..\TradingFlow.Finviz\TradingFlow.Finviz.csproj" />
    <ProjectReference Include="..\TradingFlow.Etoro\TradingFlow.Etoro.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.8" />
  </ItemGroup>
</Project>
