using TradingFlow.Domain.Market;

namespace TradingFlow.Engine.Abstractions;

/// <summary>
/// Identifies the owner of persisted candles. Scope is the runtime mode
/// (backtest, paper, or live), RunName isolates one UI/worker run, and
/// ProviderName keeps Alpaca/CSV/etc. data separated.
/// </summary>
public sealed record CandleStoreContext(
    string Scope,
    string RunName,
    string ProviderName);

/// <summary>
/// Writes a batch of candles generated by the market pipeline. Source should
/// describe where the bars came from, for example "provider" for raw feed bars
/// or "derived" for engine-resampled bars.
/// </summary>
public sealed record CandleStoreWriteRequest(
    CandleStoreContext Context,
    string Source,
    IReadOnlyCollection<OhlcvBar> Bars);

/// <summary>
/// Reads previously persisted candles for one ticker/timeframe window.
/// Store implementations can decide whether to merge multiple physical sources.
/// </summary>
public sealed record CandleStoreReadRequest(
    string Scope,
    string RunName,
    string ProviderName,
    string Ticker,
    string Timeframe,
    DateTimeOffset Start,
    DateTimeOffset End);

/// <summary>
/// Persistence boundary for candle history produced while a backtest or
/// paper/live pipeline is running. Keeping this behind an interface lets the
/// hot engine write to local files today and later swap in blob/database
/// implementations without strategy-code changes.
/// </summary>
public interface ICandleStore
{
    /// <summary>
    /// Upserts bars by timestamp. Implementations should be idempotent because
    /// live/paper runs commonly fetch overlapping lookback windows.
    /// </summary>
    Task UpsertBarsAsync(CandleStoreWriteRequest request, CancellationToken cancellationToken);

    /// <summary>
    /// Returns ordered, de-duplicated bars for the requested ticker/timeframe.
    /// </summary>
    Task<IReadOnlyList<OhlcvBar>> ReadBarsAsync(CandleStoreReadRequest request, CancellationToken cancellationToken);
}

/// <summary>
/// No-op store used by tests and CLI paths that do not need durable candle
/// spill. This keeps persistence optional at the pipeline boundary.
/// </summary>
public sealed class NullCandleStore : ICandleStore
{
    public static NullCandleStore Instance { get; } = new();

    private NullCandleStore()
    {
    }

    public Task UpsertBarsAsync(CandleStoreWriteRequest request, CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }

    public Task<IReadOnlyList<OhlcvBar>> ReadBarsAsync(CandleStoreReadRequest request, CancellationToken cancellationToken)
    {
        return Task.FromResult<IReadOnlyList<OhlcvBar>>(Array.Empty<OhlcvBar>());
    }
}
