using TradingFlow.Domain.Market;

namespace TradingFlow.Domain.Strategies;

public sealed record TradeSignal(
    string Ticker,
    DateTimeOffset Timestamp,
    string Timeframe,
    decimal CurrentPrice,
    decimal CurrentVolume,
    decimal CurrentRsi,
    decimal CurrentAtr,
    bool IsAboveVwap,
    bool IsVwapPullback,
    bool IsVwapReclaim,
    bool IsVwapRejection,
    bool IsEma20Pullback,
    bool IsOpeningRangeBreakout,
    bool IsOpeningRangeBreakdown,
    bool IsRecentHighBreakout,
    bool IsRecentLowBreakdown,
    bool IsVolatilityContraction,
    bool IsPriceAboveEma20,
    bool IsPriceAboveEma50,
    bool IsEma20AboveEma50,
    decimal? VwapExtensionAtr,
    bool IsAboveBollingerMiddle,
    bool IsMacdHistogramPositive,
    bool IsMacdNotBearish,
    decimal? PriceLogSlope = null,
    decimal? PriceLogR2 = null,
    decimal? VolumeLogSlope = null,
    decimal? VolumeLogR2 = null,
    bool IsOpeningDriveContinuation = false,
    bool IsAboveSessionOpen = false,
    bool IsBelowSessionOpen = false,
    decimal? CloseLocationValue = null,
    decimal? DayGainPct = null,
    decimal? SessionGainPct = null,
    decimal? PreEntrySessionRangePct = null,
    decimal? EntryPullbackFromSessionHighPct = null,
    CatalystEvent? Catalyst = null,
    decimal? CatalystAgeHours = null,
    decimal? CatalystPriceMovePct = null,
    bool IsBullFlagBreakout = false,
    bool IsFlatTopBreakout = false,
    decimal? BullFlagPoleMovePct = null,
    decimal? BullFlagPullbackDepthPct = null,
    decimal? BullFlagPullbackVolumeRatio = null,
    decimal? BullFlagBreakoutVolumeRatio = null,
    decimal? PremarketHigh = null,
    decimal? PremarketLow = null,
    decimal? PremarketVwap = null,
    decimal? PremarketVolume = null,
    decimal? PremarketRunPct = null,
    decimal? PremarketVwapExtensionPct = null,
    bool IsPremarketHighBreak = false,
    int? MinutesAfterRegularOpen = null,
    int ConsecutiveClosesAboveVwap = 0,
    decimal? SignalBarMidpoint = null,
    decimal? BollingerPosition = null,
    decimal? BollingerWidthPct = null,
    bool IsPriceAboveSma10 = false,
    bool IsPriceAboveSma20 = false,
    bool IsPriceAboveSma50 = false,
    bool IsSma10AboveSma20 = false,
    bool IsSma20AboveSma50 = false,
    decimal? AnchoredVwap = null,
    decimal? AnchoredVwapExtensionAtr = null,
    bool IsAboveAnchoredVwap = false,
    bool IsBelowAnchoredVwap = false,
    decimal? ShortAnchoredVwap = null,
    decimal? ShortAnchoredVwapExtensionAtr = null,
    bool IsBelowShortAnchoredVwap = false,
    bool IsStepBreakout = false,
    bool IsStepBreakdown = false,
    decimal? StepPriorMovePct = null,
    decimal? StepPriorDeclinePct = null,
    decimal? StepBaseDepthPct = null,
    decimal? StepBaseVolumeRatio = null,
    decimal? StepBreakoutVolumeRatio = null,
    decimal? StepBollingerWidthRatio = null,
    bool IsSwingReclaim = false,
    decimal? ReclaimPullbackDepthPct = null,
    decimal? ReclaimRecentHigh = null,
    decimal? ReclaimPullbackLow = null,
    bool IsSwingRollover = false,
    decimal? RolloverAdvancePct = null,
    decimal? RolloverDropFromHighPct = null,
    decimal? RolloverRecentHigh = null);
