apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: trading-flow-live-kv
  namespace: trading-flow-live
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "00000000-0000-0000-0000-000000000003"
    keyvaultName: "kv-tradingflow-live"
    tenantId: "00000000-0000-0000-0000-000000000000"
    objects: |
      array:
        - |
          objectName: alpaca-live-key-id
          objectType: secret
        - |
          objectName: alpaca-live-secret-key
          objectType: secret
  secretObjects:
    - secretName: trading-flow-live-secrets
      type: Opaque
      data:
        - objectName: alpaca-live-key-id
          key: ALPACA_KEY_ID
        - objectName: alpaca-live-secret-key
          key: ALPACA_SECRET_KEY
