using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using TradingFlow.Data.Context;
using TradingFlow.Domain.Wishlists;

namespace TradingFlow.Web.Services.Workflows;

public sealed class SectorNewsWatcherService : BackgroundService
{
    private readonly IServiceProvider serviceProvider;
    private readonly ILogger<SectorNewsWatcherService> logger;
    private readonly TimeSpan pollInterval = TimeSpan.FromMinutes(15);
    private readonly HashSet<string> processedHeadlines = new();

    public SectorNewsWatcherService(
        IServiceProvider serviceProvider,
        ILogger<SectorNewsWatcherService> logger)
    {
        this.serviceProvider = serviceProvider;
        this.logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        logger.LogInformation("Starting Sector News Watcher Service...");

        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                await RunIterationAsync(stoppingToken);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Error during Sector News Watcher iteration.");
            }

            await Task.Delay(pollInterval, stoppingToken);
        }
    }

    private async Task RunIterationAsync(CancellationToken cancellationToken)
    {
        using var scope = serviceProvider.CreateScope();
        var dbFactory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<TradingFlowDbContext>>();
        var predictorClient = scope.ServiceProvider.GetRequiredService<MarketPredictorHttpClient>();

        await using var db = await dbFactory.CreateDbContextAsync(cancellationToken);
        
        // In a real scenario, this would call FinvizNewsProvider or a global news API.
        // For now, we simulate receiving some macro headlines:
        var mockHeadlines = new List<string> 
        { 
            "US will support china with chips",
            "Trump says memory will be restricted its a down beat news all will fall"
        };

        var wishlist = await db.Wishlists
            .Include(w => w.Items)
            .FirstOrDefaultAsync(w => w.Name == "Macro Trade Suggestions", cancellationToken);

        if (wishlist == null)
        {
            wishlist = new Wishlist 
            { 
                Id = Guid.NewGuid(), 
                Name = "Macro Trade Suggestions", 
                Description = "Auto-generated by SectorNewsWatcher" 
            };
            db.Wishlists.Add(wishlist);
        }

        foreach (var headline in mockHeadlines)
        {
            if (processedHeadlines.Contains(headline)) continue;
            processedHeadlines.Add(headline);

            var (sector, sentiment) = MacroSentimentParser.ParseHeadline(headline);
            
            if (sector != "Unknown")
            {
                logger.LogInformation("Parsed Macro Headline: [{Sentiment}] for sector [{Sector}]", sentiment, sector);
                
                // If it is Upbeat, suggest correlated ETF (mock mapping)
                var correlatedEtf = GetSectorEtf(sector);
                
                if (sentiment == "Upbeat" && correlatedEtf != null)
                {
                    logger.LogInformation("Sector {Sector} is UPBEAT. Suggesting trade for {Etf}.", sector, correlatedEtf);
                    
                    if (!wishlist.Items.Any(i => i.Ticker == correlatedEtf))
                    {
                        var item = new WishlistItem 
                        { 
                            Id = Guid.NewGuid(), 
                            WishlistId = wishlist.Id, 
                            Ticker = correlatedEtf,
                            AddedAtUtc = DateTimeOffset.UtcNow,
                            Notes = $"Macro Catalyst: {headline}"
                        };
                        wishlist.Items.Add(item);
                    }
                }
                else if (sentiment == "Downbeat" && correlatedEtf != null)
                {
                    logger.LogWarning("Sector {Sector} is DOWNBEAT. Avoiding long positions for {Etf}.", sector, correlatedEtf);
                    // Could optionally short the ETF, or remove it from wishlists.
                }
            }
        }

        await db.SaveChangesAsync(cancellationToken);
    }

    private static string? GetSectorEtf(string sector)
    {
        return sector switch
        {
            "Semiconductors" => "SOXX",
            "Memory" => "MU", // Proxy
            "Automotive" => "CARZ",
            "Technology" => "XLK",
            _ => null
        };
    }
}
