<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradingFlow.Domain\TradingFlow.Domain.csproj" />
    <ProjectReference Include="..\TradingFlow.Engine\TradingFlow.Engine.csproj" />
    <ProjectReference Include="..\TradingFlow.Data\TradingFlow.Data.csproj" />
    <ProjectReference Include="..\TradingFlow.Backtesting\TradingFlow.Backtesting.csproj" />
    <ProjectReference Include="..\TradingFlow.Alpaca\TradingFlow.Alpaca.csproj" />
    <ProjectReference Include="..\TradingFlow.Web\TradingFlow.Web.csproj" />
    <ProjectReference Include="..\TradingFlow.WarmupService\TradingFlow.WarmupService.csproj" />
  </ItemGroup>

</Project>
